### ISSUE TITLE
pip3 install error: ImportError: No module named 'error'

### ISSUE THREAD

**Issue by AnthonyWC** [garabik/grc#71]
Installed grc with pip3 --user (python 3.5.2) on Ubuntu 16.04, getting this error:

```
Traceback (most recent call last):
  File "/home/antho/.local/bin/grc", line 19, in <module>
    from grc.yaml import load
  File "/home/antho/.local/lib/python3.5/site-packages/grc/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named 'error'
```

`__init__.py` calls error.py in the same directory
```
head /home/antho/.local/lib/python3.5/site-packages/grc/yaml/__init__.py

from error import *
```

**Comment by AnthonyWC** [comment]
Another PYTHONPATH issue; forgot to set to ''
